"""LaTeX tables from the run index: specs, filters, statuses, supersession, refs, escaping."""

from __future__ import annotations

import statistics
import textwrap
from collections.abc import Callable, Sequence
from typing import Any

import pytest

from qcal.config import Config, ConfigError
from qcal.integrity.aggregates import format_value
from qcal.registry.index import render_value, write_index
from qcal.registry.records import RunRecord
from qcal.registry.store import RegistryStore
from qcal.registry.tables import (
    ColumnSpec,
    TableDataError,
    TableResult,
    TableSpec,
    build_tables,
    latex_escape,
    load_specs,
    make_ref,
    render_table,
)
from tests.conftest import make_record, write

HEADER = "% Generated by `qcal registry tables` from the run index. Do not edit by hand."
SPEC = """
[[table]]
name = "main"
rows = ["detector"]

[[table.columns]]
metric = "LaECE0"
"""


def row(
    run_id: str,
    *,
    detector: str = "atss",
    precision: str = "fp32",
    status: str = "ok",
    supersedes: str = "",
    cell_id: str = "C-a",
    seed: str | None = None,
    **metrics: Any,
) -> dict[str, str]:
    data = {
        "run_id": run_id,
        "cell_id": cell_id,
        "seed": run_id if seed is None else seed,  # distinct by default: one run per seed
        "status": status,
        "supersedes": supersedes,
        "factor.detector": detector,
        "factor.precision": precision,
    }
    data.update({f"metric.{name}": render_value(value) for name, value in metrics.items()})
    return data


def spec(
    *columns: ColumnSpec,
    rows: Sequence[str] = ("factor.detector",),
    statuses: Sequence[str] = ("ok",),
    **fields: Any,
) -> TableSpec:
    return TableSpec(
        name="t",
        rows=tuple(rows),
        columns=columns or (ColumnSpec("AP", "mean", 2, "AP"),),
        statuses=tuple(statuses),
        **fields,
    )


def body(text: str) -> list[str]:
    """The data rows of a rendered table (between the header rule and the closing rule)."""
    lines = text.splitlines()
    start = next(i for i, line in enumerate(lines) if line.startswith("\\begin{tabular}"))
    end = lines.index("\\end{tabular}")
    return lines[start + 4 : end - 1]


def specs_from(config: Config, text: str, name: str = "main.toml") -> list[TableSpec]:
    write(config.root, f"configs/tables/{name}", text)
    return load_specs(config)


def build_index(config: Config, *records: RunRecord) -> None:
    store = RegistryStore(config.path("registry_dir"))
    for record in records:
        store.write(record)
    write_index(config, store)


# -- escaping and references --------------------------------------------------------------


@pytest.mark.parametrize(
    ("text", "expected"),
    [
        ("plain text 1.5", "plain text 1.5"),
        ("\\", r"\textbackslash{}"),
        ("&", r"\&"),
        ("%", r"\%"),
        ("$", r"\$"),
        ("#", r"\#"),
        ("_", r"\_"),
        ("{", r"\{"),
        ("}", r"\}"),
        ("~", r"\textasciitilde{}"),
        ("^", r"\^{}"),
        ("a_b & c%", r"a\_b \& c\%"),
        ("\\{}", r"\textbackslash{}\{\}"),
        ("", ""),
    ],
)
def test_latex_escape(text: str, expected: str) -> None:
    assert latex_escape(text) == expected


@pytest.mark.parametrize(
    ("agg", "run_ids", "expected"),
    [
        ("mean", ["R1"], "run:R1:AP"),
        ("median", ["R1"], "run:R1:AP"),
        ("min", ["R1"], "run:R1:AP"),
        ("max", ["R1"], "run:R1:AP"),
        ("sum", ["R1"], "run:R1:AP"),
        ("count", ["R1"], "agg:count:AP:R1"),
        ("std", ["R1"], "agg:std:AP:R1"),
        ("mean", ["R1", "R2"], "agg:mean:AP:R1+R2"),
        ("std", ["R1", "R2", "R3"], "agg:std:AP:R1+R2+R3"),
    ],
)
def test_make_ref(agg: str, run_ids: list[str], expected: str) -> None:
    assert make_ref(agg, "AP", run_ids) == expected


# -- loading specs ------------------------------------------------------------------------


def test_load_specs_without_spec_directory_is_empty(config: Config) -> None:
    assert load_specs(config) == []


def test_load_specs_applies_defaults(config: Config) -> None:
    (loaded,) = specs_from(config, SPEC)
    assert loaded == TableSpec(
        name="main",
        rows=("factor.detector",),
        columns=(ColumnSpec("LaECE0", "mean", 2, "LaECE0"),),
        row_headers=(),
        caption="",
        label="",
        filters={},
        statuses=("ok",),
        alignment="",
    )


def test_load_specs_reads_every_field(config: Config) -> None:
    text = """
    [[table]]
    name = "h1"
    caption = "LaECE$_0$ before and after PTQ"
    label = "tab:h1"
    rows = ["detector", "factor.precision"]
    row_headers = ["Detector", "Precision"]
    status = ["ok", "failed"]
    alignment = "llrr"

    [table.filter]
    target = "trt_jetson"
    threshold_regime = ["reuse_fp32"]

    [[table.columns]]
    metric = "LaECE0"
    agg = "median"
    digits = 3
    header = "LaECE$_0$"

    [[table.columns]]
    metric = "AP"
    """
    (loaded,) = specs_from(config, textwrap.dedent(text))
    assert loaded == TableSpec(
        name="h1",
        rows=("factor.detector", "factor.precision"),
        columns=(
            ColumnSpec("LaECE0", "median", 3, "LaECE$_0$"),
            ColumnSpec("AP", "mean", 2, "AP"),
        ),
        row_headers=("Detector", "Precision"),
        caption="LaECE$_0$ before and after PTQ",
        label="tab:h1",
        filters={"factor.target": "trt_jetson", "factor.threshold_regime": ["reuse_fp32"]},
        statuses=("ok", "failed"),
        alignment="llrr",
    )


def test_load_specs_accepts_a_single_top_level_table(config: Config) -> None:
    text = 'name = "solo"\nrows = ["detector"]\n\n[[columns]]\nmetric = "AP"\n'
    assert [s.name for s in specs_from(config, text)] == ["solo"]


def test_load_specs_reads_several_tables_per_file_and_files_in_order(config: Config) -> None:
    write(config.root, "configs/tables/b.toml", SPEC.replace('"main"', '"b1"'))
    second = SPEC.replace('"main"', '"a1"') + SPEC.replace('"main"', '"a2"')
    assert [s.name for s in specs_from(config, second, "a.toml")] == ["a1", "a2", "b1"]


def test_load_specs_only_reads_files_matching_the_glob(config: Config) -> None:
    write(config.root, "configs/tables/README.md", "# not a spec\n")
    write(config.root, "configs/tables/old.toml.bak", "garbage")
    assert [s.name for s in specs_from(config, SPEC)] == ["main"]


def test_spec_glob_is_configurable(make_config: Callable[[str], Config]) -> None:
    config = make_config('[tables]\nspec_glob = "*.table.toml"\n')
    write(config.root, "configs/tables/ignored.toml", SPEC.replace('"main"', '"ignored"'))
    assert [s.name for s in specs_from(config, SPEC, "main.table.toml")] == ["main"]


def test_load_specs_uses_configured_defaults(make_config: Callable[[str], Config]) -> None:
    config = make_config('[tables]\ndefault_agg = "median"\ndefault_digits = 4\n')
    (loaded,) = specs_from(config, SPEC)
    assert loaded.columns == (ColumnSpec("LaECE0", "median", 4, "LaECE0"),)


def test_default_status_follows_configured_ok_status(
    make_config: Callable[[str], Config],
) -> None:
    config = make_config('[registry]\nok_status = "done"\n')
    assert specs_from(config, SPEC)[0].statuses == ("done",)


@pytest.mark.parametrize(
    ("name", "expected"),
    [("detector", "factor.detector"), ("factor.detector", "factor.detector")],
)
def test_row_and_filter_keys_get_the_factor_prefix_unless_already_prefixed(
    config: Config, name: str, expected: str
) -> None:
    text = f'name = "t"\nrows = ["{name}"]\n[filter]\n"{name}" = "x"\n[[columns]]\nmetric = "AP"\n'
    (loaded,) = specs_from(config, text)
    assert (loaded.rows, dict(loaded.filters)) == ((expected,), {expected: "x"})


def test_table_key_must_be_an_array_of_tables(config: Config) -> None:
    text = '[table]\nname = "t"\nrows = ["d"]\n[[table.columns]]\nmetric = "AP"\n'
    with pytest.raises(ConfigError, match="'table' must be an array of tables"):
        specs_from(config, text)


@pytest.mark.parametrize("missing", ["name", "rows", "columns"])
def test_spec_must_name_its_required_keys(config: Config, missing: str) -> None:
    data = {"name": '"t"', "rows": '["d"]', "columns": '[{metric = "AP"}]'}
    del data[missing]
    text = "".join(f"{k} = {v}\n" for k, v in data.items())
    with pytest.raises(ConfigError, match=f"main.toml: table spec is missing '{missing}'"):
        specs_from(config, text)


@pytest.mark.parametrize(
    "text",
    [
        'name = "t"\nrows = []\ncolumns = [{metric = "AP"}]\n',
        'name = "t"\nrows = ["d"]\ncolumns = []\n',
    ],
    ids=["no-rows", "no-columns"],
)
def test_spec_needs_a_row_key_and_a_column(config: Config, text: str) -> None:
    with pytest.raises(ConfigError, match="'t' needs at least one row key and one column"):
        specs_from(config, text)


def test_duplicate_table_names_are_rejected(config: Config) -> None:
    write(config.root, "configs/tables/other.toml", SPEC)
    with pytest.raises(ConfigError, match="duplicate table names: main"):
        specs_from(config, SPEC)


@pytest.mark.parametrize(
    "columns",
    ['[{agg = "mean"}]', '[{metric = "AP", digits = "two"}]', '"AP"'],
    ids=["no-metric", "non-integer-digits", "columns-not-tables"],
)
def test_malformed_columns_are_configuration_errors(config: Config, columns: str) -> None:
    with pytest.raises(ConfigError, match=r"main\.toml"):
        specs_from(config, f'name = "t"\nrows = ["d"]\ncolumns = {columns}\n')


def test_unparseable_spec_is_a_configuration_error_naming_the_file(config: Config) -> None:
    with pytest.raises(ConfigError, match=r"broken\.toml"):
        specs_from(config, "name = \n", "broken.toml")


@pytest.mark.parametrize(
    ("text", "attribute", "expected"),
    [
        (
            'name = "t"\nrows = ["detector"]\nstatus = "failed"\ncolumns = [{metric = "AP"}]\n',
            "statuses",
            ("failed",),
        ),
        (
            'name = "t"\nrows = "detector"\ncolumns = [{metric = "AP"}]\n',
            "rows",
            ("factor.detector",),
        ),
    ],
    ids=["status", "rows"],
)
def test_bare_strings_are_one_value_or_rejected(
    config: Config, text: str, attribute: str, expected: tuple[str, ...]
) -> None:
    try:
        (loaded,) = specs_from(config, text)
    except ConfigError:
        return  # rejecting the spec is an acceptable fix too
    assert getattr(loaded, attribute) == expected


# -- rendering ----------------------------------------------------------------------------


def test_render_table_golden_output(config: Config) -> None:
    index = [row("R1", AP=41.0), row("R2", AP=42.0), row("R3", detector="detr", AP=30.5)]
    assert render_table(config, spec(), index).splitlines() == [
        HEADER,
        "\\providecommand{\\qcalval}[2]{#2}",
        "\\begin{table}[t]",
        "\\centering",
        "\\begin{tabular}{lr}",
        "\\hline",
        "detector & AP \\\\",
        "\\hline",
        "atss & \\qcalval{agg:mean:AP:R1+R2}{41.50} \\\\",
        "detr & \\qcalval{run:R3:AP}{30.50} \\\\",
        "\\hline",
        "\\end{tabular}",
        "\\end{table}",
    ]


def test_render_table_ends_with_a_newline(config: Config) -> None:
    assert render_table(config, spec(), []).endswith("\\end{table}\n")


def test_caption_and_label_follow_centering(config: Config) -> None:
    lines = render_table(config, spec(caption="Main $x$", label="tab:main"), []).splitlines()
    assert lines[3:6] == ["\\centering", "\\caption{Main $x$}", "\\label{tab:main}"]


def test_default_alignment_is_l_per_row_key_and_r_per_column(config: Config) -> None:
    columns = (ColumnSpec("AP", "mean", 2, "AP"), ColumnSpec("LRP", "mean", 2, "LRP"))
    text = render_table(config, spec(*columns, rows=("factor.detector", "factor.precision")), [])
    assert "\\begin{tabular}{llrr}" in text.splitlines()


def test_custom_alignment_is_used_verbatim(config: Config) -> None:
    assert "\\begin{tabular}{l|c}" in render_table(config, spec(alignment="l|c"), [])


def test_row_headers_override_factor_names(config: Config) -> None:
    text = render_table(config, spec(row_headers=("Detector",)), [])
    assert "Detector & AP \\\\" in text.splitlines()


def test_column_headers_are_used_verbatim(config: Config) -> None:
    text = render_table(config, spec(ColumnSpec("LaECE0", "mean", 2, "LaECE$_0$")), [])
    assert "detector & LaECE$_0$ \\\\" in text.splitlines()


@pytest.mark.parametrize(
    ("table", "expected"),
    [
        (spec(rows=("factor.threshold_regime",)), r"threshold\_regime & AP \\"),
    ],
    ids=["row-header"],
)
def test_default_headers_are_latex_escaped(config: Config, table: TableSpec, expected: str) -> None:
    assert expected in render_table(config, table, []).splitlines()


def test_default_column_header_from_spec_is_the_metric_name(config: Config) -> None:
    (loaded,) = specs_from(config, SPEC)
    assert "detector & LaECE0 \\\\" in render_table(config, loaded, []).splitlines()


def test_groups_are_sorted_by_row_key(config: Config) -> None:
    index = [row("R1", detector="yolox", AP=1), row("R2", detector="atss", AP=2)]
    assert [line.split(" & ")[0] for line in body(render_table(config, spec(), index))] == [
        "atss",
        "yolox",
    ]


def test_several_row_keys_group_jointly(config: Config) -> None:
    index = [
        row("R1", precision="int8", AP=1.0),
        row("R2", precision="fp32", AP=2.0),
        row("R3", precision="int8", AP=3.0),
    ]
    table = spec(rows=("factor.detector", "factor.precision"))
    assert body(render_table(config, table, index)) == [
        "atss & fp32 & \\qcalval{run:R2:AP}{2.00} \\\\",
        "atss & int8 & \\qcalval{agg:mean:AP:R1+R3}{2.00} \\\\",
    ]


def test_runs_in_a_reference_are_sorted_by_run_id(config: Config) -> None:
    index = [row("R3", AP=3.0), row("R1", AP=1.0), row("R2", AP=2.0)]
    assert "agg:mean:AP:R1+R2+R3" in render_table(config, spec(), index)


def test_values_use_the_column_digits(config: Config) -> None:
    index = [row("R1", AP=1.0), row("R2", AP=2.0), row("R3", AP=2.0)]
    text = render_table(config, spec(ColumnSpec("AP", "mean", 4, "AP")), index)
    assert "{1.6667}" in text


@pytest.mark.parametrize(
    ("agg", "expected"),
    [
        ("mean", statistics.fmean([1.0, 2.0, 6.0])),
        ("median", 2.0),
        ("min", 1.0),
        ("max", 6.0),
        ("sum", 9.0),
        ("count", 3.0),
        ("std", statistics.stdev([1.0, 2.0, 6.0])),
    ],
)
def test_aggregations_are_rendered_with_agg_refs(config: Config, agg: str, expected: float) -> None:
    index = [row("R1", AP=1.0), row("R2", AP=2.0), row("R3", AP=6.0)]
    text = render_table(config, spec(ColumnSpec("AP", agg, 3, "AP")), index)
    assert f"\\qcalval{{agg:{agg}:AP:R1+R2+R3}}{{{format_value(expected, 3)}}}" in text


def test_count_of_one_run_keeps_an_agg_ref(config: Config) -> None:
    text = render_table(config, spec(ColumnSpec("AP", "count", 0, "n")), [row("R1", AP=5.0)])
    assert body(text) == ["atss & \\qcalval{agg:count:AP:R1}{1} \\\\"]


def test_std_of_one_run_is_a_missing_cell(config: Config) -> None:
    text = render_table(config, spec(ColumnSpec("AP", "std", 2, "sd")), [row("R1", AP=5.0)])
    assert body(text) == ["atss & -- \\\\"]


def test_group_without_the_metric_is_a_missing_cell(config: Config) -> None:
    columns = (ColumnSpec("AP", "mean", 2, "AP"), ColumnSpec("LRP", "mean", 2, "LRP"))
    assert body(render_table(config, spec(*columns), [row("R1", AP=1.0)])) == [
        "atss & \\qcalval{run:R1:AP}{1.00} & -- \\\\"
    ]


def test_references_only_name_runs_that_have_the_metric(config: Config) -> None:
    index = [row("R1", AP=1.0), row("R2", LRP=5.0), row("R3", AP=3.0)]
    assert body(render_table(config, spec(), index)) == [
        "atss & \\qcalval{agg:mean:AP:R1+R3}{2.00} \\\\"
    ]


def test_missing_cell_marker_macro_and_layout_are_configurable(
    make_config: Callable[[str], Config],
) -> None:
    config = make_config(
        """
        [tables]
        missing_cell = "n/a"
        macro = "num"
        rule = "\\\\midrule"
        float_placement = "htbp"
        """
    )
    columns = (ColumnSpec("AP", "mean", 1, "AP"), ColumnSpec("LRP", "mean", 1, "LRP"))
    lines = render_table(config, spec(*columns), [row("R1", AP=1.0)]).splitlines()
    assert "\\providecommand{\\num}[2]{#2}" in lines
    assert "\\begin{table}[htbp]" in lines
    assert lines.count("\\midrule") == 3
    assert "atss & \\num{run:R1:AP}{1.0} & n/a \\\\" in lines


def test_row_key_values_are_latex_escaped(config: Config) -> None:
    text = render_table(config, spec(), [row("R1", detector="yolox_s&m", AP=1.0)])
    assert body(text)[0].startswith("yolox\\_s\\&m & ")


def test_rows_missing_a_row_key_group_under_an_empty_value(config: Config) -> None:
    bare = {"run_id": "R1", "status": "ok", "metric.AP": "1.0"}
    assert body(render_table(config, spec(), [bare])) == [" & \\qcalval{run:R1:AP}{1.00} \\\\"]


def test_empty_index_renders_header_only(config: Config) -> None:
    assert body(render_table(config, spec(), [])) == []


# -- selection ----------------------------------------------------------------------------


def test_only_listed_statuses_are_used(config: Config) -> None:
    index = [row("R1", AP=1.0), row("R2", status="failed", AP=9.0)]
    assert "run:R1:AP" in render_table(config, spec(), index)
    assert "R2" not in render_table(config, spec(), index)


def test_statuses_can_include_failed_runs(config: Config) -> None:
    index = [row("R1", AP=1.0), row("R2", status="failed", AP=3.0)]
    text = render_table(config, spec(statuses=("ok", "failed")), index)
    assert "\\qcalval{agg:mean:AP:R1+R2}{2.00}" in text


def test_superseded_rows_are_excluded(config: Config) -> None:
    index = [row("R1", AP=1.0), row("R2", supersedes="R1", AP=5.0)]
    assert body(render_table(config, spec(), index)) == ["atss & \\qcalval{run:R2:AP}{5.00} \\\\"]


def test_rows_superseded_by_an_unselected_row_are_still_excluded(config: Config) -> None:
    index = [row("R1", AP=1.0), row("R2", supersedes="R1", status="failed")]
    assert body(render_table(config, spec(), index)) == []


@pytest.mark.parametrize(
    ("filters", "expected_runs"),
    [
        ({"factor.precision": "int8"}, ["R2"]),
        ({"factor.precision": ["int8", "fp16"]}, ["R2", "R3"]),
        ({"factor.precision": "bf16"}, []),
        ({"factor.size": 500}, ["R1"]),
        ({"factor.scale": 0.5}, ["R2"]),
        ({"factor.tf32": False}, ["R1"]),
        ({"factor.tf32": [True]}, ["R3"]),
        ({"factor.missing": "x"}, []),
        ({"factor.precision": "fp32", "factor.tf32": False}, ["R1"]),
    ],
)
def test_filters_select_by_factor_value(
    config: Config, filters: dict[str, Any], expected_runs: list[str]
) -> None:
    index = [
        {**row("R1", precision="fp32", AP=1.0), "factor.size": "500", "factor.tf32": "false"},
        {**row("R2", precision="int8", AP=1.0), "factor.scale": "0.5"},
        {**row("R3", precision="fp16", AP=1.0), "factor.tf32": "true"},
    ]
    table = spec(rows=("run_id",), filters=filters)
    selected = [line.split(" & ")[0] for line in body(render_table(config, table, index))]
    assert selected == expected_runs


def test_boolean_filter_matches_records_written_through_the_index(config: Config) -> None:
    build_index(
        config,
        make_record("R1", factors={"detector": "atss", "tf32": False}),
        make_record("R2", factors={"detector": "atss", "tf32": True}),
    )
    write(
        config.root,
        "configs/tables/main.toml",
        SPEC + "\n[table.filter]\ntf32 = false\n",
    )
    (result,) = build_tables(config)
    assert "\\qcalval{run:R1:LaECE0}{12.50}" in result.path.read_text("utf-8")


# -- building -----------------------------------------------------------------------------


def test_build_tables_writes_one_file_per_spec(config: Config) -> None:
    build_index(
        config,
        make_record("R1", metrics={"LaECE0": 12.0}),
        make_record("R2", seed=1, metrics={"LaECE0": 13.0}),
        make_record("R3", factors={"detector": "detr"}, metrics={"LaECE0": 20.0}),
    )
    write(config.root, "configs/tables/main.toml", SPEC)
    results = build_tables(config)
    target = config.path("tables_dir") / "main.tex"
    assert results == [TableResult(target, True)]
    assert body(target.read_text("utf-8")) == [
        "atss & \\qcalval{agg:mean:LaECE0:R1+R2}{12.50} \\\\",
        "detr & \\qcalval{run:R3:LaECE0}{20.00} \\\\",
    ]


def test_build_tables_is_idempotent(config: Config) -> None:
    build_index(config, make_record("R1"))
    write(config.root, "configs/tables/main.toml", SPEC)
    build_tables(config)
    assert build_tables(config) == [TableResult(config.path("tables_dir") / "main.tex", False)]


def test_build_tables_check_reports_missing_output_without_writing(config: Config) -> None:
    write(config.root, "configs/tables/main.toml", SPEC)
    (result,) = build_tables(config, check=True)
    assert result.changed is True
    assert not result.path.exists()


def test_build_tables_check_reports_stale_output_without_touching_it(config: Config) -> None:
    write(config.root, "configs/tables/main.toml", SPEC)
    (built,) = build_tables(config)
    build_index(config, make_record("R1"))
    before = built.path.read_text("utf-8")
    (result,) = build_tables(config, check=True)
    assert result.changed is True
    assert built.path.read_text("utf-8") == before


def test_build_tables_check_passes_for_fresh_output(config: Config) -> None:
    build_index(config, make_record("R1"))
    write(config.root, "configs/tables/main.toml", SPEC)
    build_tables(config)
    assert [r.changed for r in build_tables(config, check=True)] == [False]


def test_build_tables_check_detects_hand_edited_numbers(config: Config) -> None:
    build_index(config, make_record("R1"))
    write(config.root, "configs/tables/main.toml", SPEC)
    (built,) = build_tables(config)
    built.path.write_text(built.path.read_text("utf-8").replace("{12.50}", "{11.00}"), "utf-8")
    assert [r.changed for r in build_tables(config, check=True)] == [True]


def test_build_tables_without_specs_does_nothing(config: Config) -> None:
    assert build_tables(config) == []
    assert not config.path("tables_dir").exists()


def test_build_tables_without_index_renders_empty_tables(config: Config) -> None:
    write(config.root, "configs/tables/main.toml", SPEC)
    (result,) = build_tables(config)
    assert body(result.path.read_text("utf-8")) == []


def test_build_tables_uses_configured_directories(
    make_config: Callable[[str], Config],
) -> None:
    config = make_config('[paths]\ntables_dir = "out/tex"\ntable_specs_dir = "specs"\n')
    write(config.root, "specs/main.toml", SPEC)
    (result,) = build_tables(config)
    assert result.path == config.root / "out" / "tex" / "main.tex"
    assert result.path.is_file()


def test_build_tables_reads_the_configured_index(make_config: Callable[[str], Config]) -> None:
    config = make_config('[paths]\nindex_csv = "elsewhere/index.csv"\n')
    build_index(config, make_record("R1"))
    write(config.root, "configs/tables/main.toml", SPEC)
    (result,) = build_tables(config)
    assert "run:R1:LaECE0" in result.path.read_text("utf-8")


def test_default_column_header_is_escaped_metric_name(config: Config) -> None:
    text = SPEC.replace('metric = "LaECE0"', 'metric = "latency_p50_ms"')
    (loaded,) = specs_from(config, text)
    assert r"detector & latency\_p50\_ms \\" in render_table(config, loaded, []).splitlines()


def test_explicit_headers_are_raw_latex(config: Config) -> None:
    text = SPEC.replace('metric = "LaECE0"', 'metric = "LaECE0"\nheader = "LaECE$_0$"')
    (loaded,) = specs_from(config, text)
    assert "detector & LaECE$_0$ \\\\" in render_table(config, loaded, []).splitlines()


@pytest.mark.parametrize("name", ["../escape", "a/b", "/abs", "", ".hidden", "x y"])
def test_table_names_cannot_escape_the_tables_directory(config: Config, name: str) -> None:
    with pytest.raises(ConfigError, match="table name"):
        specs_from(config, SPEC.replace('name = "main"', f'name = "{name}"'))


# -- unsound aggregates (PR-A2) -----------------------------------------------------------


def _with(rows: list[dict[str, str]], **columns: str) -> list[dict[str, str]]:
    return [{**r, **columns} for r in rows]


def test_a_row_mixing_configuration_files_is_refused(config: Config) -> None:
    index = [
        {**row("R1", AP=1.0), "config_inputs_sha256": "a" * 64},
        {**row("R2", AP=2.0), "config_inputs_sha256": "b" * 64},
    ]
    with pytest.raises(TableDataError, match="ran under different configuration files"):
        render_table(config, spec(), index)


def test_runs_under_the_same_configuration_files_are_averaged(config: Config) -> None:
    index = _with([row("R1", AP=1.0), row("R2", AP=2.0)], config_inputs_sha256="a" * 64)
    assert "{1.50}" in render_table(config, spec(), index)


def test_a_spread_over_seeds_that_drew_nothing_is_refused(config: Config) -> None:
    index = _with([row("R1", AP=1.0), row("R2", AP=1.0)], **{"env.seed_effective": "false"})
    with pytest.raises(TableDataError, match="false zero variance"):
        render_table(config, spec(ColumnSpec("AP", "std", 2, "AP")), index)
    assert "{1.00}" in render_table(config, spec(), index)  # the mean of identical runs is fine


def test_a_spread_over_seeds_that_drew_is_allowed(config: Config) -> None:
    index = _with([row("R1", AP=1.0), row("R2", AP=3.0)], **{"env.seed_effective": "true"})
    assert "{1.41}" in render_table(config, spec(ColumnSpec("AP", "std", 2, "AP")), index)
